query Posts($slug: String!) {
    posts(where: {slug: $slug}) {
        id
        slug
        title
        subtitle
        content {
      		... on ComponentPostContentBlock {
        		__typename
        		content
      		}
        	... on ComponentPostCarousel {
		        __typename
        		caption
        		images {
          		... on UploadFile {
                      url
                      previewUrl
                  }
        		}
      		}
            ... on ComponentMenuMenu {
                __typename,
                menu {
          			id
                    name
                    menu_items {
            			id
                        name
                        description
                    }
                }
            }
    	}
        featured_image {
            url
        }
    }
}
