query Posts {
    posts {
        id
        slug
        title
        subtitle
    	category
        # content
        featured_image {
            url
        }
        thumbnail_image {
            url
        }
    	published_at
    }
}
